### ISSUE TITLE
get driver not work

### ISSUE THREAD

**Issue by FreeM1ne** [DedInc/selenium_dolphin#7]
I think the reason is that I don't have the drivers for the browser, it used to download, but now it doesn't

```
Traceback (most recent call last):
  File "C:\Users\test.py", line 3, in <module>
    browser = dolphin.get_driver(port=int(open('port.txt', 'r').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\venv\Lib\site-packages\selenium_dolphin\selenium_dolphin.py", line 71, in get_driver
    driver_path = get_dolphin_driver()
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\venv\Lib\site-packages\selenium_dolphin\selenium_dolphin.py", line 36, in get_dolphin_driver
    version = driver_slices[1].split('"')[0]
              ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by DedInc** [comment]
dolphin anty removed the docs section from their site, strange, but it doesn't open in any way and it doesn't even matter if you are registered or not, for now instead of selenium and I even recommend using pyppeteer, you shouldn't have such problems there, hopefully everything will be solved with selenium as well.

**Comment by FreeM1ne** [comment]
Change the code to swap the zip into memory, i.e. there will be no unnecessary archives
You can also use  response.content instead of the stream download function
